-- INSERT ALL ITENS ON https://www.ensino.mar.mil.br/marinhafn/Lista.pdf?id_file=732 REQUESTS --
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Cadeado com duas chaves, tamanho 20mm', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Sunga de banho azul ou preta', 1, 1, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Short azul ou preto', 1, 1,2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Camisetas brancas (sem manga)', 1, 2, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Pares de meias brancas', 1, 2, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Pasta escolar polionda azul (30x25x5cm)', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Cartas pré-seladas', 1, 5, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Agulhas de costurar', 1, 2, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Apontador para lápis', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Aparelhos de barbear (descartáveis)', 1, 5, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Borracha bicolor', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Cortador de unhas', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Creme de barbear', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Creme dental grande', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Caderno universitário', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Caneta esferográfica (azul / preta / vermelha)', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Cabides', 1, 10, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Cuecas', 1, 5, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Desodorante', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Escova dental', 1, 1, 3); 
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Escovas para sapato', 1, 2, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Escovas para graxa', 1, 2, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Elástico', 1, 1, 1);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Fio dental', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Flanelas (tamanho médio para limpar metais)', 1, 2, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Graxa para calçado marrom', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Graxa para calçado preto', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Lápis', 1, 2, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Pincel para barba', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Polvilho anti-séptico', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Polidor de metais', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Pregadores de roupas', 1, 12, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Régua plástica', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Retrós de linha branca', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Retrós de linha verde musgo', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Sabonetes', 1, 2, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Saboneteira', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Barra de sabão comum', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Barra de sabão de coco', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Par de tênis para corrida (não precisa ser novo)', 1, 1, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Ferro de passar roupa', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Bolsa preta (sem marcação e com capacidade, aproximada, de 30 litros)', 1, 1, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Porta terno (preto e sem marcação)', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Repelente', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Óculos de natação', 1, 1, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Protetor solar (fator de proteção mínimo 30)', 1, 1, 3);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Calça jeans (traje civil)', 1, 1, 2);
INSERT INTO Item (ID, Nome, Status, Quantidade, Unidade) VALUES (NULL, 'Camisa de meia manga (traje civil)', 1, 1, 2);